name: "timm/vit_base_patch16_224.augreg_in21k"
loader: timm_vit
data_path: depalm-data/models/timm/vit_base_patch16_224.augreg_in21k.bin
hidden_feature_shape: [197, 768] # Or 'auto'
tokens_grid: [14, 14]